---
- name: Deploy Calculator Application
  hosts: localhost
  remote_user: khushi
  become: true

  tasks:
    - name: Install Docker and dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - docker.io
        - python3-pip
        - python3-docker

    - name: Pull the latest Docker image
      docker_image:
        name: "khushi2912/calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker pull result
      debug:
        var: docker_pull_result

    - name: Stop and remove any existing container
      shell: |
        docker stop calculator || true
        docker rm calculator || true
      ignore_errors: yes

    - name: Run the new calculator container
      docker_container:
        name: calculator
        image: "khushi2912/calculator"
        state: started
        restart_policy: always
